CREATE DATABASE [PurseDB]
GO

USE [PurseDB]

CREATE TABLE [CLIENT] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY
)

CREATE TABLE [USER] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[NAME] NVARCHAR(100) NOT NULL,
	[SHORT_NAME] NVARCHAR(10) NOT NULL,
	[EMAIL] NVARCHAR(100) NOT NULL,
	[PASSWORD] NVARCHAR(MAX) NOT NULL,
	[PHONE] NVARCHAR(100) NOT NULL,
	[CLIENT_CODE] INT NOT NULL,
	[COLOR] NVARCHAR(6) NOT NULL,
	[LAST_LOGIN] DATETIME DEFAULT GETDATE(),
	CONSTRAINT UQ_USER_EMAIL UNIQUE ([EMAIL]),
    CONSTRAINT UQ_USER_PHONE UNIQUE ([PHONE]),
    CONSTRAINT UQ_USER_NAME UNIQUE ([NAME]),
    CONSTRAINT FK_USERS_TO_CLIENT FOREIGN KEY ([CLIENT_CODE])  REFERENCES [CLIENT] ([CODE])
)

CREATE TABLE [CURRENCY] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[NAME] NVARCHAR(20) NOT NULL,
	[SYMBOL] NVARCHAR(20) NOT NULL
)

CREATE TABLE [PLAN] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[DATE_CREATE] DATETIME DEFAULT GETDATE(),
	[OWNER] INT NOT NULL,
	[START_DATE] DATETIME NOT NULL,
	[END_DATE] DATETIME NOT NULL,
	[PLANNED_BUDGET] NUMERIC(16, 2) DEFAULT 0,
	[ACTUAL_BUDGET] NUMERIC(16, 2) DEFAULT 0,
	[EXECUTORS] NVARCHAR(50) NULL,
	[CURRCODE] INT NOT NULL,
	[STATUS] INT NOT NULL,
	[IS_PRIVATE] BIT DEFAULT 0,
	CONSTRAINT FK_PLAN_TO_USERS FOREIGN KEY ([OWNER])  REFERENCES [USER] ([CODE]),
	CONSTRAINT FK_PLAN_TO_CURRENCY FOREIGN KEY ([CURRCODE])  REFERENCES [CURRENCY] ([CODE])
)

CREATE TABLE [CATEGORY_SERVICE] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[NAME] NVARCHAR(100) NOT NULL,
	[COLOR] NVARCHAR(10) NOT NULL
)

CREATE TABLE [SERVICE] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[NAME] NVARCHAR(100) NOT NULL,
	[CATEGORY_CODE] INT NOT NULL,
	CONSTRAINT FK_CATEGORY_TO_SERVICE FOREIGN KEY ([CATEGORY_CODE])  REFERENCES [CATEGORY_SERVICE] ([CODE])
)

CREATE TABLE [FLIGHT] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[PLAN_CODE] INT NOT NULL,
	[PLANNED_BUDGET] NUMERIC(16, 2) DEFAULT 0,
	[ACTUAL_BUDGET] NUMERIC(16, 2) DEFAULT 0,
	[OWNER] INT NOT NULL,
	[SERVICE_CODE] INT NOT NULL,
	[COMMENT] NVARCHAR(250) NULL,
	[STATUS] INT NOT NULL,
	[IS_PRIVATE] BIT DEFAULT 0,
	CONSTRAINT FK_FLIGHT_TO_USERS FOREIGN KEY ([OWNER])  REFERENCES [USER] ([CODE]),
	CONSTRAINT FK_FLIGHT_TO_PLAN FOREIGN KEY ([PLAN_CODE])  REFERENCES [PLAN] ([CODE]),
	CONSTRAINT FK_FLIGHT_TO_SERVICE FOREIGN KEY ([SERVICE_CODE])  REFERENCES [SERVICE] ([CODE])
)

CREATE TABLE [TEMPLATE_PLAN] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[PLAN_CODE] INT NOT NULL,
	[REPEAT] INT NULL,
	[IS_AUTO] BIT DEFAULT 0,
	CONSTRAINT FK_TEMPLATE_TO_PLAN FOREIGN KEY ([PLAN_CODE])  REFERENCES [PLAN] ([CODE])
)

CREATE TABLE [TOTALLOG] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[DESCRIPTION] NVARCHAR(MAX) NOT NULL,
	[DATEEROR] DATETIME NOT NULL
)

CREATE TABLE [SENTENCE] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[MESSAGE] NVARCHAR(MAX) NOT NULL,
	[DATE_SEND] DATETIME NOT NULL,
	[OWNER] INT NOT NULL,
	CONSTRAINT FK_SENTENCE_TO_USERS FOREIGN KEY ([OWNER])  REFERENCES [USER] ([CODE])
)
GO