CREATE DATABASE [PurseDB]
GO

USE [PurseDB]

CREATE TABLE [CURRENCY] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[NAME] NVARCHAR(20) NOT NULL,
	[SYMBOL] NVARCHAR(20) NOT NULL
)

CREATE TABLE [CATEGORY_SERVICE] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[NAME] NVARCHAR(100) NOT NULL,
	[COLOR] NVARCHAR(10) NOT NULL
)

CREATE TABLE [SERVICE] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[NAME] NVARCHAR(100) NOT NULL,
	[CATEGORY_CODE] INT NOT NULL,
	CONSTRAINT FK_CATEGORY_TO_SERVICE FOREIGN KEY ([CATEGORY_CODE])  REFERENCES [CATEGORY_SERVICE] ([CODE])
)

CREATE TABLE [USER] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[FIRST_NAME] NVARCHAR(100) NOT NULL,
	[LAST_NAME] NVARCHAR(100) NOT NULL,
	[NAME] NVARCHAR(10) NOT NULL,
	[EMAIL] NVARCHAR(100) NOT NULL,
	[PASSWORD] NVARCHAR(MAX) NOT NULL,
	[CASH] NUMERIC(16, 2) DEFAULT 0,
	[PHONE] NVARCHAR(100) NOT NULL,
	[FAMILY_CODE] INT NULL,
	[COLOR] NVARCHAR(6) NOT NULL,
	[BIRTHDAY] DATE NOT NULL,
	[CREATE_DATE] DATETIME NOT NULL,
	[LAST_LOGIN] DATETIME NULL,
	[STATUS_USER] INT DEFAULT 0,
	CONSTRAINT UQ_USER_EMAIL UNIQUE ([EMAIL]),
    CONSTRAINT UQ_USER_PHONE UNIQUE ([PHONE]),
    CONSTRAINT UQ_USER_NAME UNIQUE ([NAME]),
    CONSTRAINT FK_USERS_TO_FAMILY FOREIGN KEY ([FAMILY_CODE])  REFERENCES [FAMILY] ([CODE])
)

CREATE TABLE [FAMILY] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[CALENDAR_PERIOD_START] DATE NOT NULL,
	[CALENDAR_PERIOD_END] DATE NOT NULL,
	[OWNER_CODE] INT NOT NULL,
	[CURRCODE] INT NOT NULL,
	CONSTRAINT FK_CLIENT_TO_CURRENCY FOREIGN KEY ([CURRCODE])  REFERENCES [CURRENCY] ([CODE]),
	CONSTRAINT FK_FAMILY_USER FOREIGN KEY ([OWNER_CODE])  REFERENCES [USER] ([CODE])
)

CREATE TABLE [USER_HISTORY_CASH] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[USER_CODE] INT NOT NULL,
	[DATE_ACTION] DATETIME NOT NULL,
	[CASH] NUMERIC(16, 2) NOT NULL,
	[CATEGORY_CODE] INT NOT NULL,
	CONSTRAINT FK_HISTORY_CASH_USERS FOREIGN KEY ([USER_CODE])  REFERENCES [USER] ([CODE]),
	CONSTRAINT FK_HISTORY_CASH_CATEGORY FOREIGN KEY ([CATEGORY_CODE])  REFERENCES [CATEGORY_SERVICE] ([CODE])
)

CREATE TABLE [PLAN] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[DATE_CREATE] DATETIME DEFAULT GETDATE(),
	[OWNER] INT NOT NULL,
	[EXECUTOR] INT NULL,
	[START_DATE] DATETIME NOT NULL,
	[END_DATE] DATETIME NOT NULL,
	[PLANNED_BUDGET] NUMERIC(16, 2) DEFAULT 0,
	[ACTUAL_BUDGET] NUMERIC(16, 2) DEFAULT 0,
	[CURRCODE] INT NOT NULL,
	[STATUS] INT NOT NULL,
	[IS_PRIVATE] BIT DEFAULT 0,
	CONSTRAINT FK_PLAN_TO_OWNER FOREIGN KEY ([OWNER]) REFERENCES [USER] ([CODE]),
	CONSTRAINT FK_PLAN_TO_EXECUTOR FOREIGN KEY ([EXECUTOR]) REFERENCES [USER] ([CODE]),
	CONSTRAINT FK_PLAN_TO_FAMILY_CURRENCY FOREIGN KEY ([CURRCODE])  REFERENCES [FAMILY] ([CURRCODE])
)

CREATE TABLE [FLIGHT] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[PLAN_CODE] INT NOT NULL,
	[PLANNED_BUDGET] NUMERIC(16, 2) DEFAULT 0,
	[ACTUAL_BUDGET] NUMERIC(16, 2) DEFAULT 0,
	[OWNER] INT NOT NULL,
	[COMMENT] NVARCHAR(250) NULL,
	[CURRCODE] INT NOT NULL,
	CONSTRAINT FK_FLIGHT_TO_USERS FOREIGN KEY ([OWNER])  REFERENCES [USER] ([CODE]),
	CONSTRAINT FK_FLIGHT_TO_PLAN FOREIGN KEY ([PLAN_CODE])  REFERENCES [PLAN] ([CODE]),
	CONSTRAINT FK_FLIGHT_TO_PLAN_CURRENCY FOREIGN KEY ([CURRCODE])  REFERENCES [PLAN] ([CURRCODE])
)

CREATE TABLE [TEMPLATE_PLAN] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[PLAN_CODE] INT NOT NULL,
	[REPEAT] INT NULL,
	[IS_AUTO] BIT DEFAULT 0,
	CONSTRAINT FK_TEMPLATE_TO_PLAN FOREIGN KEY ([PLAN_CODE])  REFERENCES [PLAN] ([CODE])
)

CREATE TABLE [TOTALLOG] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[DESCRIPTION] NVARCHAR(MAX) NOT NULL,
	[DATEEROR] DATETIME DEFAULT GETDATE()
)

CREATE TABLE [SENTENCE] (
	[CODE] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[MESSAGE] NVARCHAR(MAX) NOT NULL,
	[DATE_SEND] DATETIME NOT NULL,
	[OWNER] INT NOT NULL,
	CONSTRAINT FK_SENTENCE_TO_USERS FOREIGN KEY ([OWNER])  REFERENCES [USER] ([CODE])
)
GO